[platformio]
default_envs = esp32-s3

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; ============================================================
;  DC Assistant - ESP32-S3
;  Configurado conforme datasheet ES3C28P / ES3N28P (LCDWIKI)
;  2.8" IPS 240x320 | ILI9341V | FT6336G | Audio I2S | MicroSD
;  Flash QSPI externo 16MB + PSRAM OPI interno 8MB
; ============================================================
src_dir = firmware/src
include_dir = firmware/include
data_dir = data

board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM

lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  lovyan03/LovyanGFX@^1.1.15
